version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend

  web_server:
    build: ./web_server
    container_name: web_server
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: frontend
